-- DANGER: This script resets the public schema and deletes all app data.
-- Run only when you want a clean start.

begin;
drop schema if exists public cascade;
create schema public;
grant usage on schema public to anon, authenticated, service_role;
grant all on schema public to postgres, service_role;
commit;
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id text not null,
  is_mastered boolean not null default false,
  last_reviewed_at timestamptz,
  updated_at timestamptz not null default now(),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  unique(user_id, word_id)
);

create table if not exists public.word_bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id text not null,
  updated_at timestamptz not null default now(),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  unique(user_id, word_id)
);

alter table public.user_progress add column if not exists updated_at timestamptz not null default now();
alter table public.user_progress add column if not exists is_deleted boolean not null default false;
alter table public.word_bookmarks add column if not exists updated_at timestamptz not null default now();
alter table public.word_bookmarks add column if not exists is_deleted boolean not null default false;

create index if not exists idx_user_progress_user_updated on public.user_progress(user_id, updated_at desc);
create index if not exists idx_word_bookmarks_user_updated on public.word_bookmarks(user_id, updated_at desc);

-- ──────────────────────────────────────────
-- XP / Level System
-- ──────────────────────────────────────────

-- 1) profiles 에 XP/레벨 컬럼 추가
alter table public.profiles add column if not exists total_xp integer not null default 0;
alter table public.profiles add column if not exists current_level integer not null default 1;
alter table public.profiles add column if not exists streak_days integer not null default 0;
alter table public.profiles add column if not exists last_study_date date;

-- 2) XP 이력 테이블
create table if not exists public.xp_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  xp_gained integer not null,
  reason text not null,
  word_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_xp_logs_user_created
  on public.xp_logs(user_id, created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'xp_logs_xp_gained_check'
  ) then
    alter table public.xp_logs
      add constraint xp_logs_xp_gained_check
      check (xp_gained >= 0 and xp_gained <= 100);
  end if;
end $$;

alter table public.xp_logs enable row level security;

drop policy if exists "xp_logs_select_own" on public.xp_logs;
drop policy if exists "xp_logs_insert_own" on public.xp_logs;
create policy "xp_logs_select_own" on public.xp_logs
  for select using (auth.uid() = user_id);
create policy "xp_logs_insert_own" on public.xp_logs
  for insert with check (auth.uid() = user_id);

-- 3) 레벨 정의 테이블 (공용, RLS 없이 조회 가능)
create table if not exists public.level_rewards (
  level integer primary key,
  required_xp integer not null,
  title text not null
);

insert into public.level_rewards (level, required_xp, title) values
  (1,  0,    '입문자'),
  (2,  100,  '초보자'),
  (3,  250,  '학습자'),
  (4,  500,  '중급자'),
  (5,  900,  '고급자'),
  (6,  1400, '숙련자'),
  (7,  2000, '전문가'),
  (8,  2800, '마스터'),
  (9,  3700, '그랜드마스터'),
  (10, 4800, '어휘왕')
on conflict do nothing;

-- 4) XP 부여 RPC 함수
create or replace function public.add_xp(
  p_user_id uuid,
  p_xp integer,
  p_reason text,
  p_word_id text default null
)
returns jsonb as $$
declare
  v_actor uuid := auth.uid();
  v_new_xp integer;
  v_new_level integer;
  v_today date := current_date;
  v_last_date date;
  v_streak integer;
begin
  if v_actor is null then
    raise exception 'unauthorized';
  end if;

  if p_user_id is null or p_user_id <> v_actor then
    raise exception 'forbidden';
  end if;

  if p_xp is null or p_xp < 0 or p_xp > 100 then
    raise exception 'invalid xp amount';
  end if;

  if p_reason not in ('word_correct', 'word_mastered') then
    raise exception 'invalid xp reason';
  end if;

  if p_word_id is not null and length(trim(p_word_id)) = 0 then
    raise exception 'invalid word id';
  end if;

  insert into public.profiles (id)
  values (p_user_id)
  on conflict (id) do nothing;

  -- XP 로그 기록
  insert into public.xp_logs(user_id, xp_gained, reason, word_id)
  values (p_user_id, p_xp, p_reason, p_word_id);

  -- streak 계산
  select last_study_date, streak_days
  into v_last_date, v_streak
  from public.profiles
  where id = p_user_id
  for update;

  if v_last_date is null or v_last_date < v_today - interval '1 day' then
    v_streak := 1;
  elsif v_last_date = v_today - interval '1 day' then
    v_streak := coalesce(v_streak, 0) + 1;
  -- else same day: streak unchanged
  end if;

  -- total_xp 업데이트 + streak
  update public.profiles
  set
    total_xp = coalesce(total_xp, 0) + p_xp,
    last_study_date = v_today,
    streak_days = coalesce(v_streak, 1)
  where id = p_user_id
  returning total_xp into v_new_xp;

  -- 레벨 재계산
  select max(level) into v_new_level
  from public.level_rewards
  where required_xp <= v_new_xp;

  update public.profiles
  set current_level = coalesce(v_new_level, 1)
  where id = p_user_id;

  return jsonb_build_object(
    'total_xp', v_new_xp,
    'current_level', coalesce(v_new_level, 1),
    'streak_days', coalesce(v_streak, 1)
  );
end;
$$ language plpgsql security definer set search_path = public, pg_temp;

revoke all on function public.add_xp(uuid, integer, text, text) from public;
grant execute on function public.add_xp(uuid, integer, text, text) to authenticated;

create or replace function public.touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_profiles_touch on public.profiles;
create trigger trg_profiles_touch
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_user_progress_touch on public.user_progress;
create trigger trg_user_progress_touch
before update on public.user_progress
for each row execute function public.touch_updated_at();

drop trigger if exists trg_word_bookmarks_touch on public.word_bookmarks;
create trigger trg_word_bookmarks_touch
before update on public.word_bookmarks
for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.word_bookmarks enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id);

drop policy if exists "progress_select_own" on public.user_progress;
drop policy if exists "progress_insert_own" on public.user_progress;
drop policy if exists "progress_update_own" on public.user_progress;
drop policy if exists "progress_delete_own" on public.user_progress;
create policy "progress_select_own" on public.user_progress
for select using (auth.uid() = user_id);
create policy "progress_insert_own" on public.user_progress
for insert with check (auth.uid() = user_id);
create policy "progress_update_own" on public.user_progress
for update using (auth.uid() = user_id);
create policy "progress_delete_own" on public.user_progress
for delete using (auth.uid() = user_id);

drop policy if exists "bookmark_select_own" on public.word_bookmarks;
drop policy if exists "bookmark_insert_own" on public.word_bookmarks;
drop policy if exists "bookmark_delete_own" on public.word_bookmarks;
create policy "bookmark_select_own" on public.word_bookmarks
for select using (auth.uid() = user_id);
create policy "bookmark_insert_own" on public.word_bookmarks
for insert with check (auth.uid() = user_id);
create policy "bookmark_delete_own" on public.word_bookmarks
for delete using (auth.uid() = user_id);

-- ──────────────────────────────────────────
-- 단어 시도 이력 (오답 노트 기반)
-- ──────────────────────────────────────────

create table if not exists public.word_attempt_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id text not null,
  dataset_id text not null,
  mode text not null,           -- 'CHOICE' | 'WRITE' | 'TEST'
  is_correct boolean not null,
  session_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_attempt_logs_user_created
  on public.word_attempt_logs(user_id, created_at desc);

create index if not exists idx_attempt_logs_word
  on public.word_attempt_logs(user_id, word_id, is_correct);

alter table public.word_attempt_logs enable row level security;

drop policy if exists "attempt_logs_select_own" on public.word_attempt_logs;
drop policy if exists "attempt_logs_insert_own" on public.word_attempt_logs;
create policy "attempt_logs_select_own" on public.word_attempt_logs
  for select using (auth.uid() = user_id);
create policy "attempt_logs_insert_own" on public.word_attempt_logs
  for insert with check (auth.uid() = user_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'word_attempt_logs_mode_check'
  ) then
    alter table public.word_attempt_logs
      add constraint word_attempt_logs_mode_check
      check (mode in ('CHOICE', 'WRITE', 'TEST'));
  end if;
end $$;

create or replace function public.get_wrong_notes_summary()
returns table (
  word_id text,
  dataset_id text,
  wrong_count bigint,
  correct_count bigint,
  total_count bigint,
  accuracy_pct numeric,
  last_attempted_at timestamptz
)
language sql
security invoker
as $$
  select
    wal.word_id,
    wal.dataset_id,
    count(*) filter (where wal.is_correct = false) as wrong_count,
    count(*) filter (where wal.is_correct = true) as correct_count,
    count(*) as total_count,
    round(
      (
        count(*) filter (where wal.is_correct = true)::numeric
        / nullif(count(*), 0)
      ) * 100,
      1
    ) as accuracy_pct,
    max(wal.created_at) as last_attempted_at
  from public.word_attempt_logs wal
  where wal.user_id = auth.uid()
  group by wal.word_id, wal.dataset_id
  having count(*) filter (where wal.is_correct = false) > 0
  order by wrong_count desc, last_attempted_at desc;
$$;

-- ──────────────────────────────────────────
-- API 권한(필수): authenticated/anon 접근 권한
-- schema.sql 단일 실행으로 초기 세팅을 완료하기 위해 포함
-- ──────────────────────────────────────────

grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, update, delete on table public.user_progress to authenticated;
grant select, insert, update, delete on table public.word_bookmarks to authenticated;
grant select, insert on table public.word_attempt_logs to authenticated;
grant select, insert on table public.xp_logs to authenticated;
grant select on table public.level_rewards to anon, authenticated;

grant usage, select on all sequences in schema public to authenticated;

alter default privileges in schema public grant usage, select on sequences to authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;

