-- Security hardening migration for existing databases
-- Safe to run multiple times (idempotent)

begin;

-- 1) xp_logs: xp 값 범위 제약 추가
create table if not exists public.xp_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  xp_gained integer not null,
  reason text not null,
  word_id text,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'xp_logs_xp_gained_check'
  ) then
    alter table public.xp_logs
      add constraint xp_logs_xp_gained_check
      check (xp_gained >= 0 and xp_gained <= 100);
  end if;
end $$;

-- 2) add_xp 함수 보안 강화
create or replace function public.add_xp(
  p_user_id uuid,
  p_xp integer,
  p_reason text,
  p_word_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_new_xp integer;
  v_new_level integer;
  v_today date := current_date;
  v_last_date date;
  v_streak integer;
begin
  if v_actor is null then
    raise exception 'unauthorized';
  end if;

  if p_user_id is null or p_user_id <> v_actor then
    raise exception 'forbidden';
  end if;

  if p_xp is null or p_xp < 0 or p_xp > 100 then
    raise exception 'invalid xp amount';
  end if;

  if p_reason not in ('word_correct', 'word_mastered') then
    raise exception 'invalid xp reason';
  end if;

  if p_word_id is not null and length(trim(p_word_id)) = 0 then
    raise exception 'invalid word id';
  end if;

  insert into public.profiles (id)
  values (p_user_id)
  on conflict (id) do nothing;

  insert into public.xp_logs(user_id, xp_gained, reason, word_id)
  values (p_user_id, p_xp, p_reason, p_word_id);

  select last_study_date, streak_days
  into v_last_date, v_streak
  from public.profiles
  where id = p_user_id
  for update;

  if v_last_date is null or v_last_date < v_today - interval '1 day' then
    v_streak := 1;
  elsif v_last_date = v_today - interval '1 day' then
    v_streak := coalesce(v_streak, 0) + 1;
  end if;

  update public.profiles
  set
    total_xp = coalesce(total_xp, 0) + p_xp,
    last_study_date = v_today,
    streak_days = coalesce(v_streak, 1)
  where id = p_user_id
  returning total_xp into v_new_xp;

  select max(level) into v_new_level
  from public.level_rewards
  where required_xp <= v_new_xp;

  update public.profiles
  set current_level = coalesce(v_new_level, 1)
  where id = p_user_id;

  return jsonb_build_object(
    'total_xp', v_new_xp,
    'current_level', coalesce(v_new_level, 1),
    'streak_days', coalesce(v_streak, 1)
  );
end;
$$;

-- 3) 함수 실행 권한 최소화
revoke all on function public.add_xp(uuid, integer, text, text) from public;
grant execute on function public.add_xp(uuid, integer, text, text) to authenticated;

commit;
